data:
  auto_download: true
  huggingface_repo: "TjarkGerken/eu-data"
  data_paths:
    local_data_dir: "data"
    source_data_dir: "source"
    local_output_dir: ".output"
  file_paths:
    dem_file: "ClippedCopernicusHeightProfile.tif"
    ghs_built_c_file: "GHS_BUILT_C/GHS_BUILT_C.vrt"
    ghs_built_v_file: "Clipped_GHS_Built-V-100m/Clipped_GHS_Built-V-100m.vrt"
    population_file: "Clipped_GHS_POP_3ss/Clipped_GHS_POP_3ss.vrt"
    nuts_files:
      l0: "NUTS-L0-NL.shp"
      l1: "NUTS-L1-NL.shp"
      l2: "NUTS-L2-NL.shp"
      l3: "NUTS-L3-NL.shp"
    river_polygons_file: "Hydrographie-Watercourse/Watercourse-Polygon.shp"
    land_mass_file: "Clipped_GHS_LAND-10m_Moll/Clipped_GHS_LAND-10m_Moll.vrt"
    hrst_file: "L2_estat_hrst_st_rcat_filtered_en/estat_hrst_st_rcat_filtered_en.csv"
    ghs_duc_file: "degree_of_urbanisation/GHS_DUC_NL_Extract.xlsx"
    gadm_l2_file: "NL-GADM-L2/gadm41_NLD_2.shp"
    port_file: "Port/PORT_RG_2025_Updated.shp"
    zeevart_freight_file: "Port/Zeevaart__gewicht__haven__soort_lading_19062025_160850.xlsx"
    port_mapping_file: "Port/port_id_category_lookup.xlsx"
    coastline_file: "EEA_Coastline_Polyline_Shape/Europe_coastline_raw_rev2017.shp"
    nl_forecast_file: "NL_Riskzone/nz_riskzone_ror.gml"
    electricity_consumption_file: "Electricity/Electricity.vrt"
    vierkant_stats_file: "Vierkantstatistieken/cbs_vk100_2023.gpkg"
  processing:
    resampling_method: "bilinear" # Valid values: nearest, bilinear, cubic, cubic_spline, lanczos, average, mode, gauss, max, min, med, q1, q3
    target_resolution: 30.0
    smoothing_sigma: 1.0
    target_crs: "EPSG:3035"
  hazard:
    river_zones:
      high_risk_distance_m: 50
      high_risk_weight: 1.15
      moderate_risk_distance_m: 200
      moderate_risk_weight: 1.1
      low_risk_distance_m: 500
      low_risk_weight: 1.05
    river_risk_decay:
      decay_distance_m: 7500
      enhanced_decay_factor: 6
      min_river_area_m2: 50000
    elevation_risk:
      max_safe_elevation_m: 25.0
      risk_decay_factor: 1.4
    flood_risk:
      max_safe_flood_risk: 0.3
    coastline_risk:
      coastline_multiplier: 1.1
      coastline_distance_m: 5000
  caching:
    enabled: false
    cache_dir: ".cache"
    max_cache_size_gb: 10
    auto_cleanup: true
    max_age_days: 7
    cache_strategies:
      raster_data: "persistent"
      calculations: "persistent"
      final_results: "persistent"
    logging:
      cache_operations: true
      cache_statistics: true
  exposition:
    ghs_built_c_weight: 0.30
    ghs_built_v_weight: 0.30
    population_weight: 0.13
    electricity_consumption_weight: 0.12
    vierkant_stats_weight: 0.15
    urbanisation_multipliers:
      urban_threshold: 0.6
      semi_urban_threshold: 0.4
      urban_multiplier: 1.15
      semi_urban_multiplier: 1.05
      rural_multiplier: 0.5
      urban_weight: 0.7
      semi_urban_weight: 0.3
    port_multipliers:
      port_polygon_multiplier: 1.15
      port_buffer_multiplier: 1.05
      port_buffer_distance_m: 500
    vierkant_stats_multipliers:
      number_of_occupants_multiplier: 1.05
      mean_household_size_multiplier: 1.05
      mean_houseprice_multiplier: 1.5
  relevance:
    min_economic_value: 0.05
    economic_datasets:
      gdp:
        weight: 0.25
        nuts_level: "l3"
        file_key: "gdp"
        exposition_weights:
          ghs_built_c_weight: 0.25
          ghs_built_v_weight: 0.34
          population_weight: 0.13
          electricity_consumption_weight: 0.18
          vierkant_stats_weight: 0.10
      freight:
        weight: 0.5
        nuts_level: "l3"
        file_key: "freight"
        exposition_weights:
          ghs_built_c_weight: 0.32
          ghs_built_v_weight: 0.34
          population_weight: 0.06
          electricity_consumption_weight: 0.18
          vierkant_stats_weight: 0.10
      hrst:
        weight: 0.25
        nuts_level: "l2"
        file_key: "hrst"
        exposition_weights:
          ghs_built_c_weight: 0.27
          ghs_built_v_weight: 0.36
          population_weight: 0.09
          electricity_consumption_weight: 0.18
          vierkant_stats_weight: 0.10
    economic_variables:
      - "gdp"
      - "freight"
      - "hrst"
  risk_assessment:
    n_risk_classes: 5
    weights:
      hazard: 0.1
      economic: 0.9
    ghs_built_c_class_weights:
      1: 0.0 # open spaces, low vegetation
      2: 0.0 # open spaces, medium vegetation
      3: 0.0 # open spaces, high vegetation
      4: 0.0 # water surfaces
      5: 0.5 # road surfaces
      11: 0.05 # residential, <=3m
      12: 0.1 # residential, 3-6m
      13: 0.1 # residential, 6-15m
      14: 0.15 # residential, 15-30m
      15: 0.15 # residential, >30m
      21: 0.25 # non-residential, <=3m
      22: 0.7 # non-residential, 3-6m
      23: 0.7 # non-residential, 6-15m
      24: 0.9 # non-residential, 15-30m
      25: 1.0 # non-residential, >30m
  visualization:
    figure_size: [15, 10]
    dpi: 300
  upload:
    enabled: true
  web_exports:
    enabled: true
    create_cog: true
    create_mvt: true
    cog_settings:
      compress: "LZW"
      predictor: 2
      blocksize: 512
      overview_compress: "LZW"
      overview_resampling: "average"
      auto_overviews: true
    mvt_settings:
      min_zoom: 0
      max_zoom: 14
      simplification: "drop-densest-as-needed"
      generate_ids: true
  building:
    base_floor_height: 3
    max_floors: 30
  clustering:
    risk_threshold: 0.35
    cell_size_meters: 30
    morphological_closing_disk_size: 12
    cluster_epsilon_multiplier: 6
    minimum_samples: 10
    alpha_parameter_divisor: 0.2
    hole_area_threshold: 0.10
    minimum_polygon_area_square_meters: 12_000_000
    smoothing_buffer_meters: 200
    polygon_simplification_tolerance: 50
    natural_smoothing_iterations: 3
    corner_rounding_radius: 30
    use_contour_method: true
