data:
  huggingface_repo: "TjarkGerken/eu-data"
  auto_download: true # Set to false to disable automatic downloads
  data_paths:
    local_data_dir: "eu_climate/data"
    local_output_dir: "eu_climate/output"
  file_paths:
    dem_file: "ClippedCopernicusHeightProfile.tif"
    ghs_built_c_file: "GHS_BUILT_C/GHS_BUILT_C.vrt"
    ghs_built_v_file: "Clipped_GHS_Built-V-100m/Clipped_GHS_Built-V-100m.vrt"
    population_file: "Clipped_GHS_POP_3ss/Clipped_GHS_POP_3ss.vrt"
    nuts_files:
      l0: "NUTS-L0-NL.shp"
      l1: "NUTS-L1-NL.shp"
      l2: "NUTS-L2-NL.shp"
      l3: "NUTS-L3-NL.shp"
    relevant_area_file: "RelevantArea.shp"
    river_segments_file: "ClippedRiverSegments.shp"
    river_nodes_file: "ClippedRiverNodes.shp"
    land_mass_file: "Clipped_GHS_LAND-10m_Moll/Clipped_GHS_LAND-10m_Moll.vrt"
  processing:
    resampling_method: "bilinear" # Valid values: nearest, bilinear, cubic, cubic_spline, lanczos, average, mode, gauss, max, min, med, q1, q3
    smoothing_sigma: 1.0
    target_crs: "EPSG:3035"
  caching:
    enabled: true
    cache_dir: ".cache"
    max_cache_size_gb: 10
    auto_cleanup: true
    max_age_days: 7
    cache_strategies:
      raster_data: "persistent"     # Large raster transformations cached persistently
      calculations: "persistent"   # Intermediate calculations cached persistently  
      final_results: "persistent"  # Final layer outputs cached persistently
    logging:
      cache_operations: true        # Log individual cache operations (debug mode)
      cache_statistics: true        # Log cache statistics
  exposition:
    ghs_built_c_weight: 0.2
    ghs_built_v_weight: 0.4
    population_weight: 0.4
  risk_assessment:
    n_risk_classes: 5
    weights:
      hazard: 0.4
      exposition: 0.4
      economic: 0.2
    ghs_built_c_class_weights:
      1: 0.0 # open spaces, low vegetation
      2: 0.0 # open spaces, medium vegetation
      3: 0.0 # open spaces, high vegetation
      4: 0.0 # water surfaces
      5: 0.1 # road surfaces
      11: 0.3 # residential, <=3m
      12: 0.4 # residential, 3-6m
      13: 0.5 # residential, 6-15m
      14: 0.7 # residential, 15-30m
      15: 1.0 # residential, >30m
      21: 0.1 # non-residential, <=3m
      22: 0.2 # non-residential, 3-6m
      23: 0.3 # non-residential, 6-15m
      24: 0.4 # non-residential, 15-30m
      25: 0.5 # non-residential, >30m
  visualization:
    figure_size: [15, 10]
    dpi: 300
  upload:
    enabled: true # Set to true to enable data upload to Hugging Face
  building:
    base_floor_height: 3
    max_floors: 30
